# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 670, 1281, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.loadButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.loadButton.setObjectName("loadButton")
        self.horizontalLayout_3.addWidget(self.loadButton)
        self.captureButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.captureButton.setObjectName("captureButton")
        self.horizontalLayout_3.addWidget(self.captureButton)
        self.saveButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.saveButton.setObjectName("saveButton")
        self.horizontalLayout_3.addWidget(self.saveButton)
        self.saveAsButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.saveAsButton.setObjectName("saveAsButton")
        self.horizontalLayout_3.addWidget(self.saveAsButton)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(970, 0, 301, 671))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(41)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.showRedChanelButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.showRedChanelButton.setObjectName("showRedChanelButton")
        self.verticalLayout_4.addWidget(self.showRedChanelButton)
        self.showGreenChanelButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.showGreenChanelButton.setObjectName("showGreenChanelButton")
        self.verticalLayout_4.addWidget(self.showGreenChanelButton)
        self.showBlueChanelButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.showBlueChanelButton.setObjectName("showBlueChanelButton")
        self.verticalLayout_4.addWidget(self.showBlueChanelButton)
        self.showNegativeButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.showNegativeButton.setObjectName("showNegativeButton")
        self.verticalLayout_4.addWidget(self.showNegativeButton)
        self.drowCircleButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.drowCircleButton.setObjectName("drowCircleButton")
        self.verticalLayout_4.addWidget(self.drowCircleButton)
        self.rotateButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.rotateButton.setObjectName("rotateButton")
        self.verticalLayout_4.addWidget(self.rotateButton)
        self.resetButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.resetButton.setObjectName("resetButton")
        self.verticalLayout_4.addWidget(self.resetButton)
        self.image = QtWidgets.QLabel(self.centralwidget)
        self.image.setGeometry(QtCore.QRect(0, 0, 961, 641))
        self.image.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.image.setText("")
        self.image.setObjectName("image")
        self.shapeLabel = QtWidgets.QLabel(self.centralwidget)
        self.shapeLabel.setGeometry(QtCore.QRect(10, 640, 951, 21))
        self.shapeLabel.setText("")
        self.shapeLabel.setObjectName("shapeLabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.loadButton.setText(_translate("MainWindow", "Загрузить изображение"))
        self.captureButton.setText(_translate("MainWindow", "Сделать фото с веб-камеры"))
        self.saveButton.setText(_translate("MainWindow", "Сохранить"))
        self.saveAsButton.setText(_translate("MainWindow", "Сохранить как"))
        self.showRedChanelButton.setText(_translate("MainWindow", "Показать красный канал"))
        self.showGreenChanelButton.setText(_translate("MainWindow", "Показать зелёный канал"))
        self.showBlueChanelButton.setText(_translate("MainWindow", "Показать синий канал"))
        self.showNegativeButton.setText(_translate("MainWindow", "Показать негативное изображение"))
        self.drowCircleButton.setText(_translate("MainWindow", "Нарисовть круг"))
        self.rotateButton.setText(_translate("MainWindow", "Вращение изображения"))
        self.resetButton.setText(_translate("MainWindow", "Сбросить изменения"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
